name = "weather-forecast"
main = "src/worker.ts"
compatibility_date = "2024-02-20"

[vars]
# You'll need to add your OpenWeather API key in the Cloudflare dashboard
# or using wrangler secret put OPENWEATHER_API_KEY