name = "weather-forecast"
main = "src/worker.ts"
compatibility_date = "2024-02-20"

# Build configuration
[build]
command = "npm run build"

# Pages configuration
[site]
bucket = "dist"
pages_build_output_dir = "dist"

# Worker configuration
[build.upload]
format = "service-worker"

# Routes configuration
[[routes]]
pattern = "/api/*"
script = "worker"
